### ISSUE TITLE
D$ tag ram Automatic blackboxing

### ISSUE THREAD

**Issue by TianyangL** [SpinalHDL/VexRiscv#117]
Hi:
Add `tags.generateAsBlackBox()` to  (https://github.com/SpinalHDL/VexRiscv/blob/master/src/main/scala/vexriscv/ip/DataCache.scala#L398)
and then run `sbt "runMain vexriscv.demo.GenFull"`
and then two blackbox `ways_0_tags` and `ways_0_tags_1_` can be found in the resulting file VexRiscv.v.
But, the D$ `wayCount = 1`. Through my own examination of the VexRiscv.v, I found the `ways_0_tags` was redundant, due to its output is not being used.

If I change `tags(tagsWriteCmd.address) := tagsWriteCmd.data` to `tags.write(address = tagsWriteCmd.address, data    = tagsWriteCmd.data)` in (https://github.com/SpinalHDL/VexRiscv/blob/master/src/main/scala/vexriscv/ip/DataCache.scala#L405), So it's only going to produce `ways_0_tags` . It look right.

**Comment by Dolu1990** [comment]
Hi, 

That's right, i pushed your fix proposal, all good now :)
