### ISSUE TITLE
Regression Test problem

### ISSUE THREAD

**Issue by jasonlee1001** [SpinalHDL/VexRiscv#126]
after executing 
  sbt "testOnly vexriscv.TestIndividualFeatures"
It runs many ISA, Dhrystone, Coremark tests, but finally fails with following message:

../../src/test/cpp/regression/../../resources/VexRiscvRegressionData/sim/zephyr/tests_kernel_context_rv32i.hex not found
makefile:270: recipe for target 'run' failed
make: *** [run] Segmentation fault (core dumped)

Does anyone knows how to solve this ?
"tests_kernel_context_rv32i.hex" not exist in project directories.

**Comment by Dolu1990** [comment]
Hi, when you cloned the repo, did you cloned it recursively ? (--recursive)

**Comment by jasonlee1001** [comment]
Thanks Dolu1990 !
After clone recursively, the .hex file is present.
