### ISSUE TITLE
Vexriscv smp problem

### ISSUE THREAD

**Issue by Chgavilana** [SpinalHDL/VexRiscv#133]
I try to make vexriscv smp version (well, i want to run with litex, but not use prebuild .v files), however got follow error:

VexRiscv/src/main/scala/vexriscv/demo/smp/Misc.scala:169:39: value contextWidth is not a member of spinal.lib.bus.bmb.BmbParameter
[error]     val context = Bits(unburstified.p.contextWidth bits)

also with sourceWidth and canWrite.

Any idea about it could be?

I use makefile provided in https://groups.google.com/group/linux-litex/attach/29637e67b847f/makefile?part=0.1&authuser=0&view=1

**Comment by Dolu1990** [comment]
Hi

Hoo, that makefile is a bit outdated. Branchs moved a bit. So currently, https://github.com/enjoy-digital/litex_vexriscv_smp/tree/vex_gen should be fine. 
Note that the VexRiscv/SpinalHDL repository are git submodules in vexriscv_smp. So you need to clone it recurivly.
With that update, you can specify the cache configs, the number of core, and a few things, if the netlist isn't pregenerated it will run the VexRiscv generation.
This will also be merged soon in master.
