### ISSUE TITLE
Documentation update / fix link

### ISSUE THREAD

**Issue by gregsadetsky** [SpinalHDL/VexRiscv#139]
Under [Briey SoC](https://github.com/SpinalHDL/VexRiscv/blob/master/README.md#briey-soc), there is a link to the `Pinsec SoC` which does not work right now.

I believe the URL should be replaced with https://spinalhdl.github.io/SpinalDoc-RTD/SpinalHDL/Legacy/pinsec/hardware_toplevel.html

Cheers

**Comment by Dolu1990** [comment]
Thanks !
Fixed :)
