### ISSUE TITLE
Questions . How much the max frequency we can get for EC5G.

### ISSUE THREAD

**Issue by akshar001** [SpinalHDL/VexRiscv#169]
Hello,

I am totally new to this thing and want to learn most of this thing and have found your project amazing.

My question is what is the max clock we can get for SOCs if we use EC5G family of lattice.

It might be very basic question but thought of asking it here.

**Comment by Dolu1990** [comment]
Hi,

Basicaly i do not have a flow for ECP5 FPGA, but i gess it is around the speed of a Cyclone V ?
I'm not sure.

**Comment by akshar001** [comment]
Can we runt the cpu core at 1Ghz anyhow?

**Comment by Dolu1990** [comment]
Only in simulation  ^^

On cheap FPGA you can run linux at 100 Mhz, probably with expensive FPGA you can go to 300-400 Mhz

**Comment by akshar001** [comment]
What if we use external pll system and supply it to inner fpga system clock?

**Comment by Dolu1990** [comment]
You will just make the logic go to fast and corrupt

**Comment by akshar001** [comment]
Ohkay. So there is no way we can make them run faster. What's the bottleneck here?

**Comment by Dolu1990** [comment]
CPU stall logic

**Comment by akshar001** [comment]
Is there any other way we can make this faster?

**Comment by Dolu1990** [comment]
cryo cooling ^^

**Comment by akshar001** [comment]
haha, so ultimate way to make this things faster is to make our own fpga!

**Comment by akshar001** [comment]
what we can do to avoid cpu stall logic?
Any pipeline related thing?

**Comment by Dolu1990** [comment]
you can't realy avoid that in a pipelined CPU. things from down in the stge have to propagate up

**Comment by akshar001** [comment]
XC7A35T-2CPG236C

This says it can run up to 450Mhz. Can we really do it?

**Comment by Dolu1990** [comment]
The 450Mhz advertised is about the clock tree, as soon you chain logic it will fall down realy fast

**Comment by Dolu1990** [comment]
that CPU in polarfire isn't part of the FPGA stuff, it's directly engraved in the silicon. that's why it is that fast

**Comment by akshar001** [comment]
Yes saw that. there are many more eFPGA concepts are coming

**Comment by akshar001** [comment]
I want to learn all this basic concepts and learn spinalhdl , can you guide me some way?

**Comment by akshar001** [comment]
I want to make one open source cheap fpga board with quad core vexRISC-V , 1GB RAM,HDMI,USB,WIFI,ETHERNET everything. like in under 100$ i want to sell it! Would it be cool?

**Comment by akshar001** [comment]
Okay! Wow! Let's get on with this!

**Comment by akshar001** [comment]
I will need to give you 2-3 board at-least for testing!

**Comment by Dolu1990** [comment]
> Hmm im working on having a USB host controller for linux <3

I mean that i'm already working on USB host for artyA7 and Ulx3s, could also be used for other boards

> I will need to give you 2-3 board at-least for testing!

I personnaly try to keep as few board as possible and avoid spliting my times on too many plateforms (as that's endless) XD

Please, if you bring a new board,  you have to port the SoC for it. I can help with informations.

**Comment by akshar001** [comment]
Okay. I might be going to use ECP5  - 85F.
Later if we need to port your code, i will certainly do it.

**Comment by akshar001** [comment]
So we will have 85F, DDR3 RAM 1 GB , RGMII ethernet , USB , UART , uSD CARD , WiFi/BLE in general in this board. 
Plus flexible interface of making sub-modules , like USB expander o UART expander. I will be manufacturing this in India , so i can get most of the cost to very cheaper level , I want this board to be a super cheap so that so many people can use it.

**Comment by akshar001** [comment]
@Dolu1990 have you ever used XC7K325T-2FFG900i

**Comment by Dolu1990** [comment]
No, never used FPGA outside the low cost range.

**Comment by akshar001** [comment]
I have purchased 2 of them. Let's see if i can make any board out of them. If we be able to make 400$ FPGA dev kit using this chip it would be good?

**Comment by Dolu1990** [comment]
400 $ is realy much, also, is vivado free to use for such big FPGA ?
One thing (i think) is that i don't realy see a good usage of FPGA above 100K lut ^^ 
I mean, with what do you fill such FPGA ? (sure you can fill it with non-softcore-designed CPU)

**Comment by akshar001** [comment]
Understood
