### ISSUE TITLE
Getting errors on running OpenOCD using Briey.scala cpu

### ISSUE THREAD

**Issue by anuragktl** [SpinalHDL/VexRiscv#18]
I am trying to run OpenOCD on Vex RISC-V processor from 'https://github.com/SpinalHDL/openocd_riscv'

I run the following command:
sudo src/openocd -f tcl/interface/ftdi/ft2232h_breakout.cfg -c 'set BRIEY_CPU0_YAML ../VexRiscv/cpu0.yaml' -f tcl/target/briey.cfg

This is the screenshot of output I am getting:
![image](https://user-images.githubusercontent.com/20017290/38115484-0e1bd794-3361-11e8-8daa-bf8889c016b9.png)

Do I need to modify 'briey.cfg'?

**Comment by Dolu1990** [comment]
Hi,

Which USB dongle are you using ? Normaly you should not have to change the briey.cfg.
What is your FPGA target ?
