### ISSUE TITLE
Building MuraxSOC fails

### ISSUE THREAD

**Issue by haritshukla** [SpinalHDL/VexRiscv#186]
Hello,
We are trying to build MuraxSOC for Arty-35,

It's failing 

sbt "runMain vexriscv.demo.MuraxWithRamInit" 

←[0m[←[0m←[0minfo←[0m] ←[0m←[0mLoading settings for project vexriscv-build from plugins.sbt ...←[0m
←[0m[←[0m←[0minfo←[0m] ←[0m←[0mLoading project definition from G:\Harit\Altium Reference\VexRiscv\project←[0m
error: error while loading String, class file '/modules/java.base/java/lang/String.class' is broken
(class java.lang.NullPointerException/Cannot invoke "scala.tools.nsc.Global$Run.typerPhase()" because the return value of "scala.tools.nsc.Global.currentRun()" is null)

We are using windows by the way.

**Comment by akshar001** [comment]
Issue was due to JAVA version , this project requires specific 1.2.7 sbt and JDK 8 or JDK 11

**Comment by Dolu1990** [comment]
Which java version did you had ?

**Comment by akshar001** [comment]
We had 16.0 and sbt 1.5

**Comment by akshar001** [comment]
We generated muraxSOC for Arty-35 and also synthesised it in vivado it all worked fine

**Comment by Dolu1990** [comment]
I didn't even knew there was a java 16.0 XD

> We generated muraxSOC for Arty-35 and also synthesised it in vivado it all worked fine

Cool :)

**Comment by akshar001** [comment]
Where is a scala code for murax?
We tried to find it in this repo but we didn't find it eventually

**Comment by Dolu1990** [comment]
Should be there : 
https://github.com/SpinalHDL/VexRiscv/blob/75bbb28ef62636dd0d4d3741c6e559a911fc85af/src/main/scala/vexriscv/demo/Murax.scala#L155

**Comment by akshar001** [comment]
Thanks!

**Comment by dwivedi998** [comment]
I want to download version 1.2.8 of SBT and I have downloaded a zip file, but I am unable find any installation procedure after that, Can anybody tell me what to do.

**Comment by Dolu1990** [comment]
@dwivedi998 
Hi, on which OS are you ?
