### ISSUE TITLE
Illegal instruction exception

### ISSUE THREAD

**Issue by aignacio** [SpinalHDL/VexRiscv#187]
Hey @Dolu1990,

I'm using the cfg VexRiscvAxi4WithIntegratedJtag core and I'm seeing an illegal instruction exception when cache starts fetching first batch of instructions...I'm using the hello world program available also in VexRiscV repository. Can you take a look in the waves below and give me your opinion on that?
![image](https://user-images.githubusercontent.com/5991372/121729646-9cfc4780-cae6-11eb-86aa-a51da946d6d7.png)
See the fst attached below. Also here's the assembly snippet that seems to be wrong:
![image](https://user-images.githubusercontent.com/5991372/121729980-ff554800-cae6-11eb-9f5c-eccf6a52365f.png)

[hello_world.zip](https://github.com/SpinalHDL/VexRiscv/files/6640225/hello_world.zip)
[waves.fst.zip](https://github.com/SpinalHDL/VexRiscv/files/6640223/waves.fst.zip)

**Comment by Dolu1990** [comment]
Hi,

The issue seems to me to be in the memory interconnect or in the ram you read.

reason is that what the CPU read from its ibus do not match the assembly code : 
![image](https://user-images.githubusercontent.com/4832082/121866802-94328e00-ccff-11eb-8ea3-baeaea8f705e.png)

**Comment by aignacio** [comment]
Hi @Dolu1990,
tks again, I checked and my elf loader was broken, fixed and now the CPU is working fine. Last question, is that possible to generate the smallest CPU version with AXI4 I/F?

**Comment by Dolu1990** [comment]
Hi,

> the smallest CPU version with AXI4 I/F

Yes it should be. there is a to toAxi4ReadOnly for the iBus and a  toAxi4Shared for the dbus. Then on that toAxi4Shared, you can do a toAxi4 to have a regular AXI

**Comment by aignacio** [comment]
tks!!
