### ISSUE TITLE
can this project support iCE40UP5k

### ISSUE THREAD

**Issue by fatalfeel** [SpinalHDL/VexRiscv#199]
can this project support iCE40UP5k - Icesugar

**Comment by Dolu1990** [comment]
Hi,

VexRiscv is just the CPU itself. In itself, it should be compatible with the iCE40UP5k, but what you need is a SoC. Which isn't realy the purpose of this repository.

Still, you can find Murax, which should be fine for the iCE40UP5K, but it won't use the big sram blocks.

**Comment by fatalfeel** [comment]
thanks man
