### ISSUE TITLE
why soc mmi tcl need swap_bits 

### ISSUE THREAD

**Issue by fatalfeel** [SpinalHDL/VexRiscv#205]
soc_mmi.tcl

why need this section?
proc swap_bits { bit } {
    if { $bit > 23 } {return [expr {24 + (31 - $bit)}]}
    if { $bit > 15 } {return [expr {16 + (23 - $bit)}]}
    if { $bit > 7  } {return [expr {8  + (15 - $bit)}]}
    return [expr {7 - $bit}]
}

little to endian? or to big endian?

**Comment by Dolu1990** [comment]
I don't realy know from where it come, maybe it was used to fill the ram with some initial content ?
