### ISSUE TITLE
Output of code not getting stored in vexrisc memory!!!

### ISSUE THREAD

**Issue by nikita890-art** [SpinalHDL/VexRiscv#214]
I am using riscv32-unknown-elf-gcc compiler . When I compile my C program in the terminal, it gives me errors stating that there are undefined references to "malloc", "calloc", "printf", "scanf" and "strlen".

https://drive.google.com/file/d/1JznFt-UFWtb2esSblZc4WQ2WQiJN5bHz/view?usp=sharing

I have no clue why these errors are showing up.

Please help!!!!

**Comment by Dolu1990** [comment]
I don't understand, i can see riscv64, not riscv32 in your screen shot

Can you try to compile : 
VexRiscv/src/main/c/murax/hello_world$ make all

**Comment by tomverbeure** [comment]
Here is the SW dir of one of my projects:
https://github.com/tomverbeure/jtag_uart_example/tree/master/sw

Note how it doesn’t use any of the C library functions. I have a small lib.c file with low level stuff that I wrote myself.

**Comment by nikita890-art** [comment]
Sir, in ur link, the lib.c file is not opening.
