### ISSUE TITLE
VexRiscv with debug interface stops execution after specified hardware breakpoint address

### ISSUE THREAD

**Issue by BLangOS** [SpinalHDL/VexRiscv#222]
Hi,
I am currently designing a simple hardware GDB server in order to be able to connect the GNU Debugger (GDB) directly to hardware. The design already works with software breakpoints, now I would like to use hardware breakpoints as well.

When testing I noticed that the VexRiscv is halted **after** executing the instruction at the address of the hardware breakpoint. The program counter then points to the next consecutive instruction when the processor halts.

In the GDB documentation, however, it says: "The breakpoint will stop your program just before it executes any of the code in the specified location." (see [https://sourceware.org/gdb/current/onlinedocs/gdb/Set-Breaks.html](https://sourceware.org/gdb/current/onlinedocs/gdb/Set-Breaks.html)).
My tests with GDB and VexRiscv confirm this behavior that gdb stops after but not at the breakpoint. 

The following timing diagram shows this behavior:
![grafik](https://user-images.githubusercontent.com/80284061/143562634-6f15a8b9-b682-464b-a792-ca637b8c3531.png)
There hardware breakpoint 3 is set to address 0x10122. To do this, the value 0x10123 is written with payload_address 0x4C into the `dbgbus`. Then the `haltIt` and `haltedByBreak` bits are cleared. The processor then executes a few instructions and is halted after the instruction at address 0x10122 has been executed. In the halt state the program counter shows the address 0x10126 of the next consecutive instruction. 

Is it possible to adapt the behavior of the VexRiscv hardware breakpoints to the GDB specification?

Best Regards,
Bernhard.

**Comment by Dolu1990** [comment]
It is on purpose to save area that Vex itself do not implement the full behaviour expected by GDB.

You need to make Vex jump to the breaked instruction before resuming the execution.
Either you do that externaly by pushing instruction via the debug interface, either you will have to extend the debug plugin by adding a jump interface which implement it.

So maybe, implementing some bridge between your hardware gdb server and vex could manage it ?

**Comment by BLangOS** [comment]
Your hint did help me to a certain extend. I already have a bridge betwenn the GDB-RSP Parser and the VexRiscV. There I added an inject of a backward jump to the start of the instruction and now it works. Before I presumed that the instruction at the breakpoint would be executed before the halt, but as you explained, it will not.

Nevertheless I have a problem with code that contains compressed instructions. When the Vex is halted by break I must know whether the instruction at the breakpoint is compressed or not. In case of compressed instructions the PC must be decremented by 2, otherwise by 4. Can this information be picked somewhere in the VexRiscv, maybe with injected instructions? If not, is it possible to add a bit with this information to the register at read address 0x00 of the debug interface?
Otherwise it is quite complex to get this information. In case of software breakpoints I assume that I can get get this info from checking the memory for `ebreak` or `c.ebreak` code at the breakpoint address. In case of hardware breakpoints I expect that I must store this information from the `Z1,address,kind` RSP commands, where the `kind` parameter contains this information.
I hope there is a simpler solution.

**Comment by Dolu1990** [comment]
> Can this information be picked somewhere in the VexRiscv, maybe with injected instructions? I

So the way i handle it in openocd is that i read the instruction itself by injecting the proper memory load instruction, and then decode it in openocd to figure it out.

> If not, is it possible to add a bit with this information to the register at read address 0x00 of the debug interface?

Yes, go ahead ^^, that one being tricky, no worries adding that single bit at 0x00

**Comment by BLangOS** [comment]
I got it without changing VexRiscv. I first compare PC-2 and PC-4 with the HW-Breakpoint registers. If there is no match I decode the memory below the PC for `c.ebreak` or `ebreak`.

Maybe one day when I am boring I will look for the tricky solution.

Thanks for your remarks,
Bernhard.

**Comment by Dolu1990** [comment]
> Maybe one day when I am boring I will look for the tricky solution.

What i mean, is that i'm positive for the RVC info being readable on address 0, as the other solutions are tricky ^^

**Comment by BLangOS** [comment]
The GDB-Server in hardware is now online, see: https://github.com/BLangOS/VexRiscV_with_HW-GDB_Server.

**Comment by tomverbeure** [comment]
Awesome!

**Comment by Dolu1990** [comment]
Cool :)
