### ISSUE TITLE
Debug failed 

### ISSUE THREAD

**Issue by Saqlinahamad** [SpinalHDL/VexRiscv#223]
Hi, 
I am using lattice propel tool and debugging RISCV Core with Lattice Board LFCPNX-100 in lattice propel SDK. 
While debugging I am getting following error for default program 
For the same board, I successfully debugged default program just 10 days back,

Open On-Chip Debugger 0.10.0+dev-snapshot (2021-10-14-10:56) Licensed under GNU GPL v2 For bug reports, read http://openocd.org/doc/doxygen/bugs.html 0 5 FTUSB-0 Info : only one transport option; autoselect 'jtag' none separate Warn : Transport "jtag" was already selected adapter speed: 4000 kHz E:/Saqlain/propel_builder/2.1_Beta/rvc/src/cpu0.yaml Warn : Interface already configured, ignoring adapter speed: 4000 kHz adapter_nsrst_delay: 260 jtag_ntrst_delay: 250 Info : set servers polling period to 50ms QCoreApplication::applicationDirPath: Please instantiate the QApplication object first Device List: LFCPNX-100:0x010F4043
Info : clock speed 4000 kHz 
Info : Listening on port 3333 for gdb connections Started by GNU MCU Eclipse 
Info : Listening on port 6666 for tcl connections 
Info : Listening on port 4444 for telnet connections 
Info : accepting 'gdb' connection on tcp/3333 
Info : Halt timed out, wake up GDB. Error: timed out while waiting for target halted 
Info : TAP fpga_spinal.bridge does not have IDCODE 
Info : TAP auto0.tap does not have IDCODE 
Info : TAP auto1.tap does not have IDCODE 
Info : TAP auto2.tap does not have IDCODE 
Info : TAP auto3.tap does not have IDCODE 
Info : TAP auto4.tap does not have IDCODE 
Info : TAP auto5.tap does not have IDCODE 
Info : TAP auto6.tap does not have IDCODE 
Info : TAP auto7.tap does not have IDCODE 
Info : TAP auto8.tap does not have IDCODE 
Info : TAP auto9.tap does not have IDCODE 
Info : TAP auto10.tap does not have IDCODE 
Info : TAP auto11.tap does not have IDCODE 
Info : TAP auto12.tap does not have IDCODE 
Info : TAP auto13.tap does not have IDCODE 
Info : TAP auto14.tap does not have IDCODE 
Info : TAP auto15.tap does not have IDCODE 
Info : TAP auto16.tap does not have IDCODE 
Info : TAP auto17.tap does not have IDCODE 
Info : TAP auto18.tap does not have IDCODE 
Info : TAP auto19.tap does not have IDCODE 
Info : TAP auto0.tap does not have IDCODE
Warn : Unexpected idcode after end of chain: 22 0x00000000 
Warn : Unexpected idcode after end of chain: 54 0x00000000 
Warn : Unexpected idcode after end of chain: 86 0x00000000 
Warn : Unexpected idcode after end of chain: 118 0x00000000 
Warn : Unexpected idcode after end of chain: 150 0x00000000 
Warn : Unexpected idcode after end of chain: 182 0x00000000 
Warn : Unexpected idcode after end of chain: 214 0x00000000 
Warn : Unexpected idcode after end of chain: 246 0x00000000 
Warn : Unexpected idcode after end of chain: 278 0x00000000 
Warn : Unexpected idcode after end of chain: 310 0x00000000 
Warn : Unexpected idcode after end of chain: 342 0x00000000 
Warn : Unexpected idcode after end of chain: 374 0x00000000 
Warn : Unexpected idcode after end of chain: 406 0x00000000 
Warn : Unexpected idcode after end of chain: 438 0x00000000 
Warn : Unexpected idcode after end of chain: 470 0x00000000 
Warn : Unexpected idcode after end of chain: 502 0x00000000 
Warn : Unexpected idcode after end of chain: 534 0x00000000 
Warn : Unexpected idcode after end of chain: 566 0x00000000 
Warn : Unexpected idcode after end of chain: 598 0x00000000 
Warn : Unexpected idcode after end of chain: 630 0x00000000
Warn : Unexpected idcode after end of chain: 662 0x00000000 
Error: double-check your JTAG setup (interface, speed, ...)
Error: Trying to use configured scan chain anyway... 
Error: fpga_spinal.bridge: IR capture error; saw 0x00 not 0x01 
Warn : Bypassing JTAG setup events due to errors 
Error: timed out while waiting for target halted TARGET: fpga_spinal.cpu0 - Not halted Info : Halt timed out, wake up GDB. Error: timed out while waiting for target halted 
Assertion failed: target->state == TARGET_HALTED, file src/target/vexriscv.c, line 1059

**Comment by fatalfeel** [comment]
http://fatalfeel.blogspot.com/2013/12/risc-v-on-arty-a7-35t.html?m=1
Check external jtag part make sure u are using dpinalhdl's openocd

**Comment by fatalfeel** [comment]
The idcode number already in vecriscv. its in vexriscv import pack

**Comment by Saqlinahamad** [comment]
Will you please help me in making sure about external JTAG part number

As I am new to this things 
I am just debugging RISCV Core in lattice propel SDK tool with provided board and lattice cable

**Comment by Saqlinahamad** [comment]
![Uploading 16386122061842503057841982337367.jpg…]()
![Uploading 16386122358406475496908211999732.jpg…]()

**Comment by Saqlinahamad** [comment]
I think it's GDB OpenOCD Debugging

**Comment by fatalfeel** [comment]
openocd will auto get idcode~~~where u get openocd?

**Comment by Saqlinahamad** [comment]
In Propel tool, 
We have option to debug through OpenOCD or GDB.

**Comment by fatalfeel** [comment]
I mean the openocd git address

**Comment by Saqlinahamad** [comment]
No, I haven't cloned this repo

**Comment by fatalfeel** [comment]
before my exp. i use official openocd git://git.code.sf.net/p/openocd/code is failed and using SpinalHDL/openocd_riscv is ok!

**Comment by Saqlinahamad** [comment]
The tool inbuilt is containing OpenOCD 
I am Debugging the FPGA board with GDB Openocd debugger 
As I debugged just 15-20 days back, 
Now 
I don't know why I can't able to debug,

**Comment by fatalfeel** [comment]
try again https://github.com/SpinalHDL/openocd_riscv

**Comment by Saqlinahamad** [comment]
Does it requires a build in linux OS 
or 
Cloning a directory? If Cloning a directory
In OpenOCD Setup, 
I require executable file OpenOCD.exe

**Comment by fatalfeel** [comment]
in ubuntu~i think u have a lot road to go~~~but good luck first

**Comment by Saqlinahamad** [comment]
No, I am working in Windows

**Comment by Saqlinahamad** [comment]
C:/lscc/propel/2.1/SDK/Openocd/bin/openocd.exe 

If I cloned the Vexriscv Openocd 
What should be my Openocd application path?

**Comment by Saqlinahamad** [comment]
![Uploading 16386203639899086151565018613012.jpg…]()

**Comment by Saqlinahamad** [comment]
![Uploading 16386204027864127507748923683003.jpg…]()

**Comment by fatalfeel** [comment]
u need upload to mediafire or google driver or we can not see it ~

**Comment by Saqlinahamad** [comment]
https://photos.app.goo.gl/VjTnDC71higH2DUTA

**Comment by Saqlinahamad** [comment]
Had shared the executable directory structure and path with the debug configuration I have currently

**Comment by fatalfeel** [comment]
my work system is on ubuntu PC not simulator linux , so can not help you in windows.
in ubuntu, we use terminal window to run openocd, recommend u change to ubuntu.
the gcc we also build in ubuntu, not use any sdk tools

**Comment by Saqlinahamad** [comment]
Yeah, 
I am working in ofc, and it will take some time to shift to Ubuntu, but I don't have much knowledge on Ubuntu also 
I am not able to locate this file (vexriscv.c) in my PC Directory structure 
What else can I be able to do in Windows platform only?

**Comment by Saqlinahamad** [comment]
Is it a JTAG interface target issue or 
Board Issue ?

**Comment by Dolu1990** [comment]
hmmm to me, it seems like some electrical issues. would that be possible ?
Do you have a logic analyser ? can you probe the jtag pins ?

**Comment by Saqlinahamad** [comment]
Yeah, 
Had checked the JTAG pins with probes in oscilloscope
They are working fine.

**Comment by Dolu1990** [comment]
Could you share a capture ? from the moment openocd boot ?

**Comment by Saqlinahamad** [comment]
https://photos.app.goo.gl/VjTnDC71higH2DUTA

**Comment by Saqlinahamad** [comment]
Hi @Dolu1990 , had captured the Debug of my SW Build over a FPGA board
Please reply me 
As soon as possible

**Comment by tomverbeure** [comment]
@Saqlinahamad 
You need to be more specific about what you're trying to do and what you're trying to archieve.

It seems like you're using a version of OpenOCD that comes standard with the Lattice Propel Tool. The default version of OpenOCD does not support the VexRiscv. As @fatalfeel already wrote multiple times: you have to use the VexRiscv openocd version that you can find at https://github.com/spinalhdl/openocd_riscv.

In the picture that you're attaching, I see "RISCV_AHBLite_RPC_DRAM_Controller_SV...". I see a press release that shows that [Lattice Propel has its own RISC-V CPU](https://www.yahoo.com/now/lattice-propel-design-environment-supports-200000942.html). This makes me question: what design are you actually using? Are you using the Propel RISC-V CPU?

If so, you're asking your question in the wrong forum. This project is about the VexRiscv, a RISC-V CPU that has nothing to do with the Lattice RISC-V.

**Comment by fatalfeel** [comment]
if you insist work on windows 
try download cygwin64 
http://www.cygwin.com
enable devel option for development gcc

build https://github.com/spinalhdl/openocd_riscv at windows
But I am not sure work or not~

**Comment by Saqlinahamad** [comment]
Okay
But, I need to produce debug results with Lattice RISC-V only. 
Thanks
