### ISSUE TITLE
The GenFullWithCSRWithFPU core has wrong about (&) (andi) instruct

### ISSUE THREAD

**Issue by sheldonyk** [SpinalHDL/VexRiscv#229]

**Comment by sheldonyk** [comment]
The andi instruct (&) is equal to xor instruct (^), i guess this maybe a bug.

**Comment by sheldonyk** [comment]
thanks

**Comment by sheldonyk** [comment]
After I updated the code, I found that this problem has been solved. Thank you.

**Comment by Dolu1990** [comment]
Hi ^^
Good, so, all good ?

**Comment by sheldonyk** [comment]
yes，i had test the RV32IMF，which the test case you provided in the project is pass



发自我的iPhone


------------------ Original ------------------
From: Dolu1990 ***@***.***&gt;
Date: Thu,Dec 30,2021 11:53 PM
To: SpinalHDL/VexRiscv ***@***.***&gt;
Cc: sheldonyk ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [SpinalHDL/VexRiscv] The GenFullWithCSRWithFPU core has wrongabout (&amp;) (andi) instruct (Issue #229)





 
Hi ^^
 Good, so, all good ?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Dolu1990** [comment]
ok, thanks ^^
