### ISSUE TITLE
Strange uart print when enabling cache and compressed instructions. 

### ISSUE THREAD

**Issue by hqd7777** [SpinalHDL/VexRiscv#252]
Hi, I find a very strange issue when I play with the Briey SOC with cache and C. The software project I use is the UART example in VexRiscvSocSoftware and I also compile it with compressed instructions enabled. When I debug it using riscvgdb and riscv openocd, I find printing error only if I set a breakpoint before the loop and then debug step by step. For example I set breakpoint at line 21
	print("Hello !\n");
It will print "Hello!" correctly and change the line. However, the characters after that will be messed up. Only when you use continue other than step can make the output correct after few outputs. 
![525338579853994061](https://user-images.githubusercontent.com/59237227/167824452-a8a4ddc7-9067-479b-824b-c2f533a78a48.png)

By the way any breakpoints inside the loop nor debug without using step will not cause that error.

**Comment by Dolu1990** [comment]
Hooo that's a very interresting bug. It was on hardware or in simulation ?

**Comment by Dolu1990** [comment]
Could you send me the exact omdification made to briey ? (especialy as you enabled RVC)

**Comment by Dolu1990** [comment]
Got the issue reproduced in simulation <3
I'm on it.

**Comment by hqd7777** [comment]
> On my side this fix the issue : [4fff62d](https://github.com/SpinalHDL/VexRiscv/commit/4fff62d3feeb05edcea46e66b25de0ecf3f274fa)
> 
> Let's me know if things aren't going well on your side ^^

Wow,I am going to check it on my simulation. Thank you very much!

**Comment by hqd7777** [comment]
> On my side this fix the issue : [4fff62d](https://github.com/SpinalHDL/VexRiscv/commit/4fff62d3feeb05edcea46e66b25de0ecf3f274fa)
> 
> Let's me know if things aren't going well on your side ^^

It seems to work on my side too. I really appreciate for your help!

**Comment by Dolu1990** [comment]
cool thanks ^^
