### ISSUE TITLE
Similar debug issue with briey soc

### ISSUE THREAD

**Issue by hqd7777** [SpinalHDL/VexRiscv#254]
Hi, 
Similar to previous issue[https://github.com/SpinalHDL/VexRiscv/issues/252], I also find an issue in simulation when prediction is set as dynamic target.
1. Openocd will crash using step by step in the while loop. I forget how I exactly make it, but it causes a core dumped using gdb step.
![2](https://user-images.githubusercontent.com/59237227/168717323-12c4b97b-cc95-4095-bcf2-f73b0050e871.png)
2. Similar to my previous ask, when I set a breakpoint at line 21 in main.c and then using step by step debug, it seems to be stuck at some point.
![3](https://user-images.githubusercontent.com/59237227/168717362-09d46f31-c68c-43a4-8637-2983719d2728.png)

prediction = DYNAMIC_TARGET
compressedGen = true

**Comment by hqd7777** [comment]
If I use the stepi at the beginning, it seems that I will be trapped in the bss loop and never jump out

**Comment by hqd7777** [comment]
For the first issue, it seems to jump to an incorrect address at line 32 of uart.h. I suppose that 0x3a is invalid for this one right?

**Comment by Dolu1990** [comment]
Ahhhh damned
And it was with the exact same setup, (briey soc, only branch prediction changed + RVC)  ?

> 0x3a

Which 0x3a ?

**Comment by hqd7777** [comment]
> Ahhhh damned And it was with the exact same setup, (briey soc, only branch prediction changed + RVC) ?
> 
> > 0x3a
> 
> Which 0x3a ?

Yes, I just changed the branch prediction. 
I mean when you use gdb stepi command at line 32, it seems to read instruction from address 0x0000003a.

**Comment by hqd7777** [comment]
Actually the program is still running. But only the first letter will print and show on the screen. That might not be prediction error.

**Comment by Dolu1990** [comment]
> step by step

So not instruction step by step, but C step by step right ?
Step in / step out / regular step ? can you describe exactly the scenario ?

**Comment by Dolu1990** [comment]
Ahhh i reproduced something, i'm on it ^^

**Comment by Dolu1990** [comment]
I just pushed another fix, i hope now all bugs are fixed ^^
Let's me know if you hit anything weird.

**Comment by hqd7777** [comment]
> I just pushed another fix, i hope now all bugs are fixed ^^ Let's me know if you hit anything weird.

Thank you Charles. I am living in China and therefore not able to reply your message on time. Apologyze for unprecise descriptions that make you confused. I appreciate for your help to fix those issues.

**Comment by Dolu1990** [comment]
>  I am living in China and therefore not able to reply your message promptly.  ApologyzeC for unprecise descriptions that make you confused.

No worries ^^

> It also fix the bugs on my side. I suppose you may close this issue.

Nice !
Thanks for the bug reporting :)
