### ISSUE TITLE
FPU Synthesis Detail

### ISSUE THREAD

**Issue by gyh1997127** [SpinalHDL/VexRiscv#256]
Hi, 

Can someone provide more details on the synthesis data shown? i.e. did the synthesis run include FP register file, instruction decode/issue logic? Much appreciated! 
> Fpu 32 bits ->
  Artix 7 relaxed -> 135 Mhz 1786 LUT 1778 FF 
  Artix 7 FMax    -> 205 Mhz 2101 LUT 1778 FF 
Fpu 64/32 bits ->
  Artix 7 relaxed -> 101 Mhz 3336 LUT 3033 FF 
  Artix 7 FMax    -> 165 Mhz 3728 LUT 3175 FF

**Comment by Dolu1990** [comment]
naxriscv => https://github.com/SpinalHDL/NaxRiscv/blob/main/src/main/scala/naxriscv/execute/fpu/FpuCore.scala

**Comment by gyh1997127** [comment]
Thank you!
