### ISSUE TITLE
Half precision floating point

### ISSUE THREAD

**Issue by lapnd** [SpinalHDL/VexRiscv#271]
Hi,
Do you support Scalar FP16?
I tried to find it in the source code but could not find FP16.
Any chance of adding an FP16 to Vexriscv?
Thank you!

**Comment by Dolu1990** [comment]
Hi,
FP16 aren't supported, and currently there is no plan to add support for it.
My guess is that it would not be necessarly hard to add, but probably time consuming.
Regards
Charles

**Comment by lapnd** [comment]
Thank you @Dolu1990
