### ISSUE TITLE
All-Zeros Instruction 

### ISSUE THREAD

**Issue by hqd8888** [SpinalHDL/VexRiscv#281]
Hello, when I try using all zeros instruction to go into trap, I find vex seems not to support it in compressed cores. It will convert the instruction to c.addi4spn but miss to check if imm is 0. I wonder if I could add a when statement to make all zeros instruction as illegal instruction with no side effects.

**Comment by Dolu1990** [comment]
Hi,

I think this should fix it : 
https://github.com/SpinalHDL/VexRiscv/commit/36c3346e51a6d9b19acb12e0aaab4632f8822ff4

let's me know how it goes ^^

**Comment by hqd8888** [comment]
> Hi,
> 
> I think this should fix it : [36c3346](https://github.com/SpinalHDL/VexRiscv/commit/36c3346e51a6d9b19acb12e0aaab4632f8822ff4)
> 
> let's me know how it goes ^^

Actually I made similar fix on my side and I am sure it works. I just want to confirm such modification will not affect other sections. ^^

**Comment by Dolu1990** [comment]
Ahhh nice, cool :)
