### ISSUE TITLE
object VJtagBridge is not a member of package spinal.lib.system.debugger

### ISSUE THREAD

**Issue by quantrpeter** [SpinalHDL/VexRiscv#282]
hi, i can't compile it, please help
![image](https://user-images.githubusercontent.com/50471577/202432829-4f123920-2541-4e25-82a0-c7f25b38ffc6.png)

```
java -version
openjdk version "1.8.0_352"
OpenJDK Runtime Environment (build 1.8.0_352-8u352-ga-1~22.04-b08)
OpenJDK 64-Bit Server VM (build 25.352-b08, mixed mode)
```

**Comment by LongStudy** [comment]
I'm running this project for the first time, and the same error appear in ubuntu 20 and ubuntu 18

[error] /mnt/d/VexRiscv/src/main/scala/vexriscv/plugin/DebugPlugin.scala:4:8: object VJtagBridge is not a member of package spinal.lib.system.debugger
[error] import spinal.lib.system.debugger.{JtagBridge, JtagBridgeNoTap, VJtagBridge, SystemDebugger, SystemDebuggerConfig, SystemDebuggerMemBus}
[error]        ^
[error] /mnt/d/VexRiscv/src/main/scala/vexriscv/plugin/DebugPlugin.scala:175:26: not found: type VJtagBridge
[error]     val jtagBridge = new VJtagBridge(jtagConfig)
[error]                          ^
[error] two errors found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 36 s, completed Nov 18, 2022 10:45:20 AM

**Comment by siluks-plumerai** [comment]
workarund, just remove this `VJtagBridge` from `DebugPlugin.scala`
![obraz](https://user-images.githubusercontent.com/73934968/202689769-ee54f8f3-b65a-4e01-89a8-42cb055d29ea.png)

**Comment by Dolu1990** [comment]
Hi,

It was due to a PR merged in masted instead of dev. the situation is now fixed :)
