### ISSUE TITLE
I can't pass all Test

### ISSUE THREAD

**Issue by xie-1399** [SpinalHDL/VexRiscv#283]
When I excute  sbt "testOnly vexriscv.TestIndividualFeatures", it faild in the test.Thank You!

![628fc18d04ce3660f0a58eae8b88d6b](https://user-images.githubusercontent.com/62367053/202459017-e49a9e29-650d-4033-bc12-6bc368779327.png)

**Comment by Dolu1990** [comment]
Hi,

Did you cloned the repo recursively ? (there is some sub git to provide big binaries for the regressions)

**Comment by xie-1399** [comment]
Thank You！
