### ISSUE TITLE
How to reset default soc clock frequency on FPGA？

### ISSUE THREAD

**Issue by JuzhongZheng666** [SpinalHDL/VexRiscv#284]
Hi，I want to set the soc clock frequency, when I load the bitstream to the FPGA. How can I do it?
I try to add 'soc_kwargs' syntex as fllow:
![image](https://user-images.githubusercontent.com/86361064/205083892-32f9b129-cd2a-4fb0-942b-6e9d402c245b.png)

But I meet this error:
![1669907611571](https://user-images.githubusercontent.com/86361064/205089239-5cc11c7b-5636-482c-b531-99a10615d5d6.jpg)
![4355ca0bcb174362bf629c0fbbbc1cb](https://user-images.githubusercontent.com/86361064/205089337-43932cba-a22b-4c39-b74c-716e6f739a8a.png)

**Comment by Dolu1990** [comment]
Hi,

I'm not sure myself about how to do it the right way with Litex.
Looking at def __init__(self, sys_clk_freq=125e6, with_led_chaser=True, with_pcie=False, **kwargs): from the litex-board, i would say you can : 
Board.__init__(self, sys_clk_freq= ???, ...) ?

(overall the VexRiscv isn't the right repo to ask the question XD)

**Comment by JuzhongZheng666** [comment]
Thank you for your answer very much. I will try. Sorry for ask this question here, I guess I make a mistake.
