### ISSUE TITLE
How to Support C extension

### ISSUE THREAD

**Issue by xie-1399** [SpinalHDL/VexRiscv#286]
Hi，when I use compressedGen = true to support C ISA extension, it builds failed，Can you help me?
![YK(3CM2@A`8C$ 81~1) 350](https://user-images.githubusercontent.com/62367053/205859211-9b19639a-0e4d-4207-ba36-6bf9c970445d.png)

**Comment by Dolu1990** [comment]
See https://github.com/SpinalHDL/VexRiscv#regfileplugin :)
