### ISSUE TITLE
what Artix board can run vexriscv?

### ISSUE THREAD

**Issue by quantrpeter** [SpinalHDL/VexRiscv#292]
hi, what Artix board can run vexriscv? thanks

**Comment by Dolu1990** [comment]
Hi,

Mainly, Artiy A7 NexysA7 and digilent video i would say.
See Litex or SaxonSoc.

https://github.com/litex-hub/linux-on-litex-vexriscv
https://github.com/SpinalHDL/SaxonSoc/tree/dev-0.3/bsp/digilent

**Comment by quantrpeter** [comment]
thanks, this board also ok https://www.quantr.foundation/2022/12/porting-litex-vex-riscv-to-icesugar-pro/
