### ISSUE TITLE
Illegal instruction execptions during speculative execution with branch prediction not being aborted properly?

### ISSUE THREAD

**Issue by bunnie** [SpinalHDL/VexRiscv#296]
The setup is a VexRiscV RV-32IMAC core with STATIC branch prediction enabled, running code in SV32 mode (MMU on).

The code in question looks like this:

```
ffd0e7f0 <memcpy>:
ffd0e7f0:	00000317          	auipc	t1,0x0
ffd0e7f4:	ed630067          	jr	-298(t1) # ffd0e6c0 <compiler_builtins::mem::memcpy>
ffd0e7f8:         <illegal instruction>
ffd0e7fa:         <illegal instruction>
```

What happens in this case is that the pipeline fetches the `jr` instruction at `ffd0e7f4`, and because `static` prediction is on, it will dutifully also fetch whatever is at `ffd0e7f8` and `ffd0e7fa` and try to execute them.

However, if those are illegal instructions, an illegal instruction trap is thrown, and the CPU handles it even though it's due to instructions that should never have been executed in the first place.

![image](https://user-images.githubusercontent.com/1168375/212889442-740efc32-d4a8-444b-98d4-d9b14b9d5d05.png)

Above is a trace of the execution at the moment this happens.

The top line is the execution PC. I have highlighted in yellow the two instructions that are fetched, but are bogus (I think in this case the first one actually decodes, the second one is illegal).

Instead of going to the jump target specified at 0xffd0e6c0, it goes to 0xffd00640 -- the location of the trap handler. You can see that `exceptionValid` is thrown, with a payload code of `2` which is an illegal instruction.

I *think* this is actually a CPU bug, because I would imagine that instructions being speculatively executed should have no impact on the pipeline if they are on the "not taken" path -- even if they are illegal instructions? I can't find mention of how this is to be handled in the RISC-V spec, though.

Normally this doesn't show up because most branches are followed by "legal instructions", but in this case, these are the very last instruction in the `.text` region, which turns out to be a `jr`, and immediately adjacent is `.rodata` which can contain some stuff that isn't guaranteed to be legal (turns out it often is a legal instruction...but not always!).

For now I have a work-around of sticking an "endcap" of NOP instructions after the last bit of code loaded into the `.text` region. Curious if you think this is actually a bug or not @Dolu1990 ?

**Comment by Dolu1990** [comment]
Hi,
Yes it is a bug.
I tried to reproduce the issue but unsucessfuly.
![image](https://user-images.githubusercontent.com/4832082/212899671-96b50b75-1209-4453-9c45-f98ed2569df5.png)
```asm
80000000 <_start>:
80000000:	0100006f          	j	80000010 <jump1>

80000004 <jump2>:
80000004:	0300006f          	j	80000034 <pass>
	...

80000010 <jump1>:
80000010:	00000013          	nop
80000014:	00000317          	auipc	t1,0x0
80000018:	ff030067          	jr	-16(t1) # 80000004 <jump2>
	...
80000024:	0040006f          	j	80000028 <fail>
``` 

So a few questions : 
- Can you send me the full wave file (all the signals of the CPU)?
- What CPU configuration do you have ? (especialy i$ ? d$ ?)

**Comment by Dolu1990** [comment]
Hoo also, which VexRiscv githash were you using ?

**Comment by bunnie** [comment]
I'm diverged slightly from the main branch because I haven't re-merged after you accepted the PR:

```
commit 2297f8aea0133f3304bdc6493bdb157d66fce63d (HEAD -> expose-satp, buncram/expose-satp)
Author: buncram <cramium@kosagi.com>
Date:   Mon Jan 16 02:16:25 2023 +0800

    also need to expose privilege state

    turns out SATP is not enough to figure out what code you're running,
    because the kernel code is mapped into all userspace's virtual memory
    areas. You also need the privilege state to be exported.

    This creates an option to export those bits.

commit 11f391eadf21fe96ef5b50d6f67512c5f2d42226
Merge: b8604790 bf3521f8
Author: buncram <cramium@kosagi.com>
Date:   Tue Dec 20 19:31:15 2022 +0800

    Merge remote-tracking branch 'origin/expand-satp' into expose-satp

commit bf3521f86a424736168fec1741e4a187fc758cad (origin/expand-satp)
Author: bunnie <bunnie@kosagi.com>
Date:   Tue Dec 20 19:25:47 2022 +0800

    Expand SATP register to 22 bits per spec

    Vex only implements a 32-bit PA which does not take advantage
    of the potetnial 32-bit space in Sv32 mode. Very reasonably,
    Vex simply discards the top two unused bits.

    However, the spec does require that the register occupy all 22
    bits and it is possible for the OS to use the extra bits up top
    for some bookkeeping purpose. This commit proposes to expand the
    register to occupy the full 22 bits in case an OS is written
    to utilize the full width of the register as written in the spec.

commit b86047901ae55a3ea0dc892acf1e72c2f0012118
Author: buncram <cramium@kosagi.com>
Date:   Mon Dec 19 19:03:33 2022 +0800

    add flag to expose SATP externally

commit 51b69a1527c01616f386fa5cffb993313bfec919 (spinalhdl/master, buncram/master)
Merge: 87c8822f 773f268f
Author: Dolu1990 <charles.papon.90@gmail.com>
Date:   Mon Dec 5 20:10:58 2022 +0100

    SpinalHDL 1.8.0
```

So basically based off of 51b69a1527c01616f386fa5cffb993313bfec919 (which should be in your tree); 2297f8aea0133f3304bdc6493bdb157d66fce63d from my tree (https://github.com/buncram/VexRiscv).

I should rebase to your branch now that the PR has been absorbed...

**Comment by Dolu1990** [comment]
Hmm, can't reproduce the issue. Note i'm using Verilator which do not have x-propagation, so it may be related to that, as i can see there is some X in the data path.

So, the issue i have is that the wave you send do not have some key signal to debug.

Would there be a way for me to run your simulation on my side ?

**Comment by bunnie** [comment]
Hm yah, I could see this just being an X-propagation thing that leads to a signal being interpreted in a weird way. Maybe in synthesized hardware the bug can't even trigger?

Anyways, let me try to prepare a script + artifacts so you can run with a single command line and an archive. It'll take a couple hours because I'm still running a simulation right now that will take another hour to finish.

Sounds like you have access to Xilinx `xsim`, so if I prepared an archive + gave you a command line you should be able to fire up the simulation.

**Comment by bunnie** [comment]
Alright, I've packed up the simulation so you should be able to just unzip and run it:

https://bunniefoo.com/bunnie/vexsim.zip

Unzip, and go into the vexsim directory, and run this command:

`xsim top_tb_fpga_sim -gui`

Should just be able to just hit the play button, set it for about 130ms (milliseconds) run-to duration, and then come back about an hour later, you should see a result a bit like this:

![image](https://user-images.githubusercontent.com/1168375/213008195-5f38c2e0-9e99-49f6-8b56-f1eae56008e9.png)

**Comment by bunnie** [comment]
Confirmed glbl.v is missing, here it is:

https://bunniefoo.com/bunnie/glbl.v

**Comment by Dolu1990** [comment]
> Hm yah, I could see this just being an X-propagation thing that leads to a signal being interpreted in a weird way. Maybe in synthesized hardware the bug can't even trigger?

Yes, this is a possibility, kind of a pain to have to deal with simulation artefacts.
I'm not saying it is the issue, but can be.

 > https://bunniefoo.com/bunnie/VexRiscv_CramSoC.v

The requested URL /bunnie/VexRiscv_CramSoC.v was not found on this server.

Thanks :)

**Comment by bunnie** [comment]
oops! fixed now.

**Comment by Dolu1990** [comment]
(Note that all the verification of VexRiscv is done with Verilator, which doesn't do x-prop)

Thanks ^^

**Comment by Dolu1990** [comment]
Get a : 

```
xsim top_tb_fpga_sim -gui
ERROR: Please check the snapshot name which is created during 'xelab',the current snapshot name "xsim.dir/top_tb_fpga_sim/xsimk" does not exist 
```

Do you know what kind of magic it is ?

**Comment by Dolu1990** [comment]
Ahhh my bad for that one i missed one command.

New error => 
Cannot find design unit work.test_tb_fpga

**Comment by Dolu1990** [comment]
So, seems like the test_tb_fpga module is missing ?

**Comment by bunnie** [comment]
My bad, I gave the wrong command (I used `test` instead of `top`; normally this is filled in by my script, I translated by hand):

`xelab -debug off top_tb_fpga glbl -s top_tb_fpga_sim -L unisims_ver -L unimacro_ver -L SIMPRIM_VER -L secureip -L $xsimdir/xil_defaultlib -timescale 1ns/1ps`

**Comment by Dolu1990** [comment]
Thanks, simulation is running now ^^

**Comment by Dolu1990** [comment]
So, yeah, it was false positive xprop : 
![image](https://user-images.githubusercontent.com/4832082/213171825-53eb15e2-72a2-4e27-a10b-841d0e2d7228.png)

Basicaly, in VexRiscv, there is multiple interface which can ask to jump somwere, and they are ordered with some priorities.
Here, in yellow, is your JR instruction correcting the CPU excecution path via the Branch plugin.
But at the same time, there is the fetch predictor (cyan) which get confused because of x-prop.

Even if that fetch predictor has less priority than the Branch plugin, because of simulation only xprop, it mess up priority logic.

So, overall the question now is how to avoid those simlation artefacts :
- I would say, having memories initialized with values instead of X may be enough.
- I don't know if there is xsim option to avoid X initialisation, and instead having random values.
- Else could implement some counter mesure in the VexRiscv for simulation purposes, but don't know how deep this would need to be digged in.

Thanks for the xsim testbench :D

**Comment by bunnie** [comment]
Thanks for running the analysis! When the kernel actually boots (instead of crashing) you can get the whole console log and everything printing out, and the results very closely match what happens on real hardware.

I'm trying to trace back where the X-prop originally comes from. I can see in the simulation that the predicted memory location being fetched has a value, it is not X -- at least, I can see the write to SRAM happening, during the initialization phase, and I would imagine this would be fetched in as part of a full cache line anyways. The memory layout is `.text` followed by `.sdata` directly, and the loader copies everything without skipping any locations. Besides, for the SRAM model, I do actually set `0` to all locations on testbench init, to avoid x-prop issues.

So I guess that leaves the question of where the X is coming from.

I will run the simulation again and have a look back in the pipeline to try and find where the X-value comes from, since there should be no X-memory at that point in execution, and let you know if I find anything interesting.

**Comment by Dolu1990** [comment]
hmmm i'm taking a look too

**Comment by Dolu1990** [comment]
Ahhhhh XD
Found it. So basicaly it come from the RVC decompressor.
When 16 bits instruction is out of the specification, in VexRiscv it is set to "don't care" 32 bits decompressed instruction.
decompressed := 32'hXXXXXXXX
Because anyway, that value will not be used and it will instead 

I pushed the fix in both dev and master branch.

Thanks :D

**Comment by Dolu1990** [comment]
So, with that fix : 
- In real hardware and in simulation, it allows to properly catch illegal RVC instruction
- In simulation, it will also avoid this x-prop of doom

**Comment by Dolu1990** [comment]
I'm running now a sim with the fix 

Turned  
IBusCachedPlugin_decompressor_decompressed = 32'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; // @[Bits.scala 231:20]  
into
IBusCachedPlugin_decompressor_decompressed = 32'd0; // @[Bits.scala 231:20]

**Comment by Dolu1990** [comment]
Seems like in simulation it fixed it.

**Comment by bunnie** [comment]
Awesome! I will pull in the fix then. I think we're all set! thanks for the speedy fix.

**Comment by bunnie** [comment]
Confirmed fixed in my simulation as well. thanks!
