### ISSUE TITLE
make run DEBUG_PLUGIN_EXTERNAL=yes bug

### ISSUE THREAD

**Issue by xie-1399** [SpinalHDL/VexRiscv#301]
Hi ,when I excute
sbt "runMain vexriscv.demo.GenFull"
make run DEBUG_PLUGIN_EXTERNAL=yes
Can you help me , thank you
![f432d1c9aeb789d8e1d4b80cd28ec72](https://user-images.githubusercontent.com/62367053/219952466-93adba30-4bb6-4562-8a40-474ffc856e06.png)
![9459a1b34c113fdb6f1c5554834a36e](https://user-images.githubusercontent.com/62367053/219952470-7ce54290-ef34-471f-9987-afe93276451d.png)

**Comment by Dolu1990** [comment]
Hi, i think it is due to a verilator version missmatch, they changed a few API functions.

Personnaly i have : 

```verilator
rawrr@rawrr:~$ verilator --version
Verilator 4.216 2021-12-05 rev v4.216-32-gfd45be3d
```
