### ISSUE TITLE
64-bit VexRiscv

### ISSUE THREAD

**Issue by YiminGao0113** [SpinalHDL/VexRiscv#302]
I wanted to ask if you have plans for implementing a 64-bit version of VexRiscv. How much amount of work will that require? Thanks!

**Comment by Dolu1990** [comment]
Hi,
fondamentaly, there would not be that much work on the harwdare dev side. maybe 80 hours ?
But the verification side would require quite some time, also, the VexRiscv verification model also need to be ported to 64 bits, so quite some work too XD so maybe 120 hours for the verification.
