### ISSUE TITLE
How Can I support the Daisy-chain debugging

### ISSUE THREAD

**Issue by xie-1399** [SpinalHDL/VexRiscv#308]
Hello，if I want to support the Daisy-chain debugging with the vexriscv ,  what should I do ? can you show me some examples , Thank you very much! 

what's more , When i excute src/openocd -c "set VEXRISCV_YAML PATH_TO_THE_GENERATED_CPU0_YAML_FILE" -f tcl/target/vexriscv_sim.cfg , there are some mistakes
![a35e409a10f5e167c738053529069c1](https://user-images.githubusercontent.com/62367053/221558993-dc5d8e3e-9cb9-4c2d-8d20-3346d4f6323b.png)

**Comment by Dolu1990** [comment]
Hi,

So daisy chain multiple JTAG ? Is your screen shot from a simulated target ? or a real target (can see vexriscv_sim.cfg)

**Comment by xie-1399** [comment]
Hi,

I want to implement daisy chain with multiple vexriscv cpu and we can debug these cpus by JATG ， Maybe like this
 
![cfa447b3c1b084f7fc370a5622ae333](https://user-images.githubusercontent.com/62367053/221561813-e7d5655d-deca-4fbf-a44d-20ec3176177a.png)

**Comment by Dolu1990** [comment]
Ahh you want to debug multiple VexRiscv CPU that are in the same device ?

**Comment by xie-1399** [comment]
Hi,

In the different devices and can Connect them by Jtag ，Maybe this picture is more appropriate
![f9f01e6cd4fc1e8233730b0ba3f5b4f](https://user-images.githubusercontent.com/62367053/221568865-94c96157-4154-4f93-bac4-e5a85ff6330c.png)

**Comment by xie-1399** [comment]
In fact each device have one vexriscv cpu，But I don't know how to achieve this chain

**Comment by Dolu1990** [comment]
So, as it is in your last picture is right :)

**Comment by Dolu1990** [comment]
Thing is you will need to adapte the openocd script to specify each tap on the chain, starting from the device 0

**Comment by xie-1399** [comment]
yeah ! AndI think Vexriscv can support this chain(*^_^*)

**Comment by xie-1399** [comment]
I try to use the openocd script like this , But It can't work fine

interface dummy
set  _ENDIAN little
set _TAP_TYPE 1234

if { [info exists CPUTAPID] } {
   set _CPUTAPID $CPUTAPID
} else {
  # set useful default
   set _CPUTAPID 0x10001fff
}
adapter_khz 4000
adapter_nsrst_delay 260
jtag_ntrst_delay 250
transport select jtag

set _CHIPNAME fpga_spinal
set _CHIP1 riscv_1
set _CHIP0 riscv_0

jtag newtap $_CHIP0 bridge -expected-id 0x80022001 -irlen 4 -ircapture 0x1 -irmask 0x1F
jtag newtap $_CHIP1 bridge -expected-id $_CPUTAPID -irlen 4 -ircapture 0x1 -irmask 0x1F
#Add Jtag Tap

target create $_CHIP0 vexriscv -endian $_ENDIAN -chain-position $_CHIP0.bridge -coreid 0 -dbgbase 0xF00F0000
target create $_CHIP1 vexriscv -endian $_ENDIAN -chain-position $_CHIP1.bridge -coreid 1 -dbgbase 0xF00F0000

vexriscv readWaitCycles 12
vexriscv cpuConfigFile $VEXRISCV_YAML
vexriscv networkProtocol iverilog

**Comment by Dolu1990** [comment]
I don't understand vexriscv networkProtocol iverilog

You are running a simulation ? or real hardware ?

**Comment by xie-1399** [comment]
running a simulation，like the vexriscv_sim.cfg

**Comment by Dolu1990** [comment]
could you share a wave file of the simulation when openocd try to connect ?
