### ISSUE TITLE
Bug report: fmin with one NaN does not always copy the other operand

### ISSUE THREAD

**Issue by flaviens** [SpinalHDL/VexRiscv#312]
Hi there!

I've detected a bug in VexRiscv.

## Brief bug description

Some float to float instructions that do not take a rounding mode, such as `fmin.s`, provide wrong results, differing by one from the expectation.

### Snippet

Here is an example RISC-V (rv32imfd) snippet:
```
  .section ".text.init","ax",@progbits
  .globl _start
  .align 2
_start:
  # Enable the FPU
  li t0, 0x2000
  csrs mstatus, t0
  csrw	fcsr,x0

  li t0, 0x5ddca7e3
  la t1, .fdata0

  fcvt.s.wu	ft0,t0,rdn
  // ft0 = 0xffffffff4ebbb94f = 1.57474e+09 (single precision interpretation)
  // ft1 = 0x7ff8000000000000 = nan (single precision interpretation)

  fmin.s ft2, ft0, ft1

  li t2, 0x18
  fsd ft0, 0(t2)
  fsd ft2, 0(t2)

  sw x0, (x0)

infinite_loop:
  jal	x0,infinite_loop

.section ".fdata0","ax",@progbits
  .8byte 0x7ff8000000000000
```

### Expected and actual results

We expect `ft2 = ft0 = 0xffffffff4ebbb94f`. I verified this with Spike.
However,  VexRiscv returns `ft0 = 0xffffffff4ebbb94f` but `ft2 = 0xffffffff4ebbb950`.

The specification says, regarding `fmin.s`:
> If only one operand is a NaN, the result is the non-NaN operand.

## Fix

Even though I'm very unfamiliar with Vexriscv and SpinalHDL, I'll be very happy to help fix this issue!

## Notes

The root cause is probably common with #310 

Thanks!
Flavien

**Comment by Dolu1990** [comment]
https://github.com/SpinalHDL/VexRiscv/commit/5f67075e3094f1f31b7fe9f480e08fc5c32b28c3 seems to fix it too
