### ISSUE TITLE
Bug report: imprecise square root

### ISSUE THREAD

**Issue by flaviens** [SpinalHDL/VexRiscv#313]
Hi there!

I've detected a bug in VexRiscv.

## Brief bug description

Square root instructions, such as `fsqrt.s`, sometimes provide wrong results, differing by one from the expectation.

### Snippet

Here is an example RISC-V (rv32imfd) snippet:
```
  .section ".text.init","ax",@progbits
  .globl _start
  .align 2
_start:
  # Enable the FPU
  li t0, 0x2000
  csrs mstatus, t0
  csrw	fcsr,x0

  li t0, 0x7FFFFFFF
  fcvt.s.w ft0, t0, rtz
  // ft0 = 0xffffffff4effffff = 2.14748e+09 (single precision interpretation)

  fsqrt.s ft1, ft0, rdn

  li t2, 0x18
  fsd ft1, 0(t2)

  sw x0, (x0)

infinite_loop:
  jal	x0,infinite_loop
```

### Expected and actual results

We expect `ft1 = 0xffffffff473504f2`. I verified this with Spike.
However,  VexRiscv returns `ft0 = 0xffffffff473504f3` but `ft2 = 0xffffffff4ebbb950`.

## Notes

The root cause is probably common with #310 and #312 because if I replace the conversion `fcvt.s.w ft0, t0, rtz` with a `fld` that results in the same value for `ft0`, then the inaccuracy disappears.

Thanks!
Flavien

**Comment by Dolu1990** [comment]
https://github.com/SpinalHDL/VexRiscv/commit/5f67075e3094f1f31b7fe9f480e08fc5c32b28c3 Seems to fix it.
