### ISSUE TITLE
Bug report: conversion from double to simple floating precision then back does not clear enough bits in the mantissa

### ISSUE THREAD

**Issue by flaviens** [SpinalHDL/VexRiscv#314]
Hi there!

I've detected a bug in VexRiscv.

## Brief bug description

One way of clearing bottom bits in a mantissa is to convert a double-precision floating-point number into single precision and back. However, VexRiscv does not clear enough bits.

### Snippet

Here is an example RISC-V (rv32imfd) snippet:
```
  .section ".text.init","ax",@progbits
  .globl _start
  .align 2
_start:
  # Enable the FPU
  li t0, 0x2000
  csrs mstatus, t0
  csrw	fcsr,x0

  la t0, .fdata0
  fld ft0, (t0)
  fcvt.s.d ft1, ft0
  fcvt.d.s ft2, ft1

  li t2, 0x18
  fsd ft2, 0(t2)

  sw x0, (x0)

infinite_loop:
  jal	x0,infinite_loop

.section ".fdata0","ax",@progbits
  .8byte 0x41e000620a000000
```

### Expected and actual results

We expect `ft2 = 0x41e0006200000000`. I verified this with Spike.
However,  VexRiscv returns `ft0 = 0x41e000620a000000` .

## Notes

The root cause is probably common with #310 , #312 and #313 given that replacing `fcvt.s.d ft1, ft0` with a floating load that gives the same floating-point value makes the problem disappear.

Thanks!
Flavien

**Comment by Dolu1990** [comment]
https://github.com/SpinalHDL/VexRiscv/commit/5f67075e3094f1f31b7fe9f480e08fc5c32b28c3 seems to fix it too
