### ISSUE TITLE
Bug report: non-strict single-precision floating point comparisons (fle.s, feq.s) may return 0 even though the operands are equal

### ISSUE THREAD

**Issue by flaviens** [SpinalHDL/VexRiscv#316]
Hi there!

I've detected a bug in VexRiscv.

## Brief bug description

The instructions `fle.s` and `feq.s` must return `1` when the two operands are equal. Under certain conditions, they return `0` even though the operands are equal.

### Snippet

Here is an example RISC-V (rv32imfd) snippet:
```
  .section ".text.init","ax",@progbits
  .globl _start
  .align 2
_start:
  # Enable the FPU
  li t0, 0x2000
  csrs mstatus, t0
  csrw	fcsr,x0

  li t0, 0xFFFFFFFF
  fcvt.s.wu	ft0,t0,rtz

  la t0, .fdata0
  fld ft1, 0(t0)

  // Here, ft0 = ft1 = 0xffffffff4f7fffff

  fle.s	t0,ft0,ft1

  li t2, 0x10
  sw t0, 0(t2)

  sw x0, (x0)

infinite_loop:
  jal	x0,infinite_loop

.section ".fdata0","ax",@progbits
  .8byte 0xffffffff4f7fffff
```

### Expected and actual results

We expect `t0 = 1`. I verified this with Spike.
However,  VexRiscv returns `t0 = 0`.

## Notes

There may be commonality in the root cause with #310, #311, #312, # 313, #314 , #315 .

Thanks!
Flavien

**Comment by Dolu1990** [comment]
https://github.com/SpinalHDL/VexRiscv/issues/317 Seems to fix it.

(it was f32 operation not removing the lsb precision bits at the end of the rounding)
