### ISSUE TITLE
Bug report: single-precision multiplication or division followed by conversion sets wrong bits in the mantissa

### ISSUE THREAD

**Issue by flaviens** [SpinalHDL/VexRiscv#321]
Hi there!

I've detected a bug in VexRiscv.

## Brief bug description

A single-precision multiplication or division followed by a single-to-double precision conversion may set wrong bits in the mantissa.
This suggests that 5f67075 did not cover all cases. Consequences are likely to be similar to the bugs that 5f67075 intended to fix.

I ran this code on master (b29eb54) where I cherry-picked the fix 5f67075, with the configuration described in #318 .

## Example instance

Here are 2 snippets, one with multiplication and one with division.

### Snippet 1

Here is an example RISC-V (rv32imfd) snippet:
```
  .section ".text.init","ax",@progbits
  .globl _start
  .align 2
_start:
  # Enable the FPU
  li t0, 0x2000
  csrs mstatus, t0
  csrw	fcsr,x0

  la t0, .fdata0
  fld fs1, (t0)

  fmul.s fa5, fs1, fs1
  fcvt.d.s ft7, fa5

  li t0, 0x18
  fsd ft7, 0(t0)

  sw x0, (x0)

infinite_loop:
  jal	x0,infinite_loop

.section ".fdata0","ax",@progbits
  .8byte 0xffffffff1cb31090 # fs1
```

#### Waveform

[Here is a waveform for snippet 1.](https://github.com/SpinalHDL/VexRiscv/files/10888359/fmulfcvt.zip)

#### Expected and actual results

We expect `ft7 = 0x373f500000000000`. I verified this with Spike.
However,  VexRiscv sets additional bits in the mantissa.

### Snippet 2

```
  .section ".text.init","ax",@progbits
  .globl _start
  .align 2
_start:
  # Enable the FPU
  li t0, 0x2000
  csrs mstatus, t0
  csrw	fcsr,x0

  la t0, .fdata0
  fld fa3, (t0)
  la t0, .fdata1
  fld fa4, (t0)

  fdiv.s   ft4,fa3,fa4,rup
  fcvt.d.s fa4, ft4

  li t0, 0x18
  fsd fa4, 0(t0)

  sw x0, (x0)

infinite_loop:
  jal	x0,infinite_loop

.section ".fdata0","ax",@progbits
  .8byte 0xffffffff8002666c # fa3
.section ".fdata1","ax",@progbits
  .8byte 0xffffffff41800000 # fa4
```

#### Expected and actual results

We expect `fa4 = 0xb773330000000000`. I verified this with Spike.
However,  VexRiscv returns `fa4 = 0xb773336000000000` .

Thanks!
Flavien

**Comment by Dolu1990** [comment]
Thanks :D
I will check all of this + others issues asap
By the way, what are you using to generate the test vectors ?
Are you specificaly targetting the fpu tests ?

**Comment by flaviens** [comment]
Sounds good! I'm using a new technique, which does not focus on FPUs, but the technique lets us observe that FPUs are generally particularly buggy. Once it is is public, I'll be happy to share it and support so you can use it yourself directly :slightly_smiling_face:.

**Comment by Dolu1990** [comment]
see #322 resolution
