### ISSUE TITLE
Bug report: non-strict single-precision floating point comparisons (fle.s, feq.s) may return 0 even though the operands are equal (returns)

### ISSUE THREAD

**Issue by flaviens** [SpinalHDL/VexRiscv#323]
Hi there!

I've detected a bug in VexRiscv, with symptom similar to #316 but not fixed by 5f67075.

## Brief bug description

The instruction  `feq.s` must return `1` when the two operands are equal. Under certain conditions, it returns `0` even though the operands are equal.

I ran this code on master (b29eb54) where I cherry-picked the fix 5f67075, with the configuration described in #318 .

### Snippet

Here is an example RISC-V (rv32imfd) snippet:
```
  .section ".text.init","ax",@progbits
  .globl _start
  .align 2
_start:
  # Enable the FPU
  li t0, 0x2000
  csrs mstatus, t0
  csrw	fcsr,x0

  li a3, 0

  la t0, .fdata0
  fld ft1, (t0)
  la t0, .fdata1
  fld fa3, (t0)

  fmul.s  fa4, fa3, ft1
  feq.s   a3, fa3, fa4

  li t0, 0x10
  sw a3, 0(t0)

  sw x0, (x0)

infinite_loop:
  jal	x0,infinite_loop

.section ".fdata0","ax",@progbits
  .8byte 0xffffffff3f800001 # ft1
.section ".fdata1","ax",@progbits
  .8byte 0xffffffff00000001 # fa3
```

### Expected and actual results

We expect `t0 = 1`. I verified this with Spike.
However,  VexRiscv returns `t0 = 0`.

Thanks!
Flavien

**Comment by Dolu1990** [comment]
see #322 resolution
