### ISSUE TITLE
Bug report: VexRiscv overcounts the retired instructions

### ISSUE THREAD

**Issue by flaviens** [SpinalHDL/VexRiscv#341]
Hi there!

### Bug description

I think I found a bug not described in the issues and PRs in this repo.
`minstret` seems to overcount.

### Example snippet

The stored value of `t0` should be `0`, however with Vexriscv it is `1`.

```
  .section ".text.init","ax",@progbits
  .globl _start
  .align 2
_start:

  li a0, 0x10

  csrrw zero, minstret, zero
  csrrw t0, minstret, zero

  sw t0, (a0)
  sw zero, (zero)

infinite_loop0:
  j infinite_loop0
```

Thanks!

**Comment by Dolu1990** [comment]
Hmm it is quite possibly due to csrrw	x0,minstret,x0  which once it get commited increase minstret ? While on spike it increase first and then set to zero ?

**Comment by flaviens** [comment]
Yes exactly. I simplified the example snippet above.
Interestingly, the expected behavior is very clearly stated in the 1.12 privileged spec:
> Any CSR write takes effect after the writing instruction has otherwise completed.
However, this explicit mention is absent from the 1.10 version, but this clarification is also omitted from the changelog in the 1.12 privileged spec, hence I suppose that the behavior better explained in 1.12 is also the one expected from 1.10.
It's probably not the most critical mismatch Vexriscv got in its life, though :disguised_face:  .

**Comment by Dolu1990** [comment]
Hmmm, for now i kind of thinking a "won't fix" is ok :)

Thanks anyway :D

**Comment by flaviens** [comment]
Yeah I understand :)
