### ISSUE TITLE
Does "MANAGEMENT" a customized INSTRUCTION?

### ISSUE THREAD

**Issue by ZhengJuzhong666** [SpinalHDL/VexRiscv#344]
Hi, I see this in "DBusCachedPlugin.scala". Does "MANAGEMENT" a customized instruction? I didn't find this instruction in  ”RISC-V Instruction Set Manual“.

![image](https://github.com/SpinalHDL/VexRiscv/assets/127759020/c98dbe7c-f9c9-4715-b4f6-2dbbd562234e)

**Comment by Dolu1990** [comment]
Hi,

Yes right it is a customized instruction to allow l1 data cache invalidation
See https://github.com/SpinalHDL/VexRiscv#dbuscachedplugin

**Comment by ZhengJuzhong666** [comment]
Thank you！It‘s a good design.
