### ISSUE TITLE
How the Jtag works when I load the Program?

### ISSUE THREAD

**Issue by xie-1399** [SpinalHDL/VexRiscv#348]
Hi！
How can I capture the wave if I want to use the debug and gdb service in the simulation?
I want to kown how the JTAG works when I load the elf program

I run the command like this: Thnak you very much!
sbt "runMain vexriscv.demo.GenFull" cd src/test/cpp/regression make run DEBUG_PLUGIN_EXTERNAL=yes  #In the openocd git, after building it => src/openocd -c "set VEXRISCV_YAML PATH_TO_THE_GENERATED_CPU0_YAML_FILE" -f tcl/target/vexriscv_sim.cfg  

#Run a GDB session with an elf RISCV executable (GenFull CPU) 
YourRiscvToolsPath/bin/riscv32-unknown-elf-gdb VexRiscvRepo/src/test/resources/elf/uart.elf target remote localhost:3333 monitor reset halt load continue

**Comment by Dolu1990** [comment]
Hi,

If you want, you can use : 
https://github.com/SpinalHDL/VexRiscv#murax-soc

(sbt "test:runMain vexriscv.MuraxSim")

To get the wave, you can add .withFstWave to SimConfig : 
https://github.com/SpinalHDL/VexRiscv/blob/c52433575dec04f10063b2fd7cebd0545c8b1be9/src/test/scala/vexriscv/MuraxSim.scala#L25
