### ISSUE TITLE
MAC custom instruction implementation

### ISSUE THREAD

**Issue by Shris7** [SpinalHDL/VexRiscv#369]
Hello, i was trying to create a custom instruction for mac operation but due to a combinatorial loop I am unable to realize it. Could you give any suggestions to implement the same?
This is what i was trying to implement:
rd := rd + (rs1*rs2)

**Comment by Dolu1990** [comment]
VexRiscv only support 2 register sources, here you add a third one as rd.
A few people i think have some patches to add a third register source.
