### ISSUE TITLE
Does it use physical address or virtual address?

### ISSUE THREAD

**Issue by chshibo** [SpinalHDL/VexRiscv#39]
We are looking for a microcontroller that uses physical address access, so we can reduce some implementation complexity. I am wondering whether the generic VexRiscv core uses physical address or virtual address?

**Comment by Dolu1990** [comment]
Hi, 
The default VexRiscv cores aren't using MMU, so they use physical address directly.
There is an example of the MMU plugin instanciation : 
https://github.com/SpinalHDL/VexRiscv/blob/master/src/main/scala/vexriscv/demo/GenFull.scala#L56
