### ISSUE TITLE
Adding VexRiscV as a dependency

### ISSUE THREAD

**Issue by DanielMadmon** [SpinalHDL/VexRiscv#390]
how can I add VexRiscV as a dependency to the sbt template?

**Comment by Dolu1990** [comment]
See here : 
https://github.com/SpinalHDL/SpinalTemplateSbtDependencies

**Comment by DanielMadmon** [comment]
thank you, it's working perfectly.

**Comment by parthkalgaonkar** [comment]
Is there a way I can add VexRiscv as a dependency in a mill project?
