### ISSUE TITLE
Problems with adding FPU in Briey

### ISSUE THREAD

**Issue by 15936866194** [SpinalHDL/VexRiscv#400]
Add FPU to Briey as follows
![image](https://github.com/SpinalHDL/VexRiscv/assets/143673576/3aa3e0b8-6804-4c41-b463-baaf921497d4)
Compiled with the MABI=ilp32f MARCH = rv32imf compile option, pc points to the exception entry address when a floating-point instruction is encountered
The assembly code is as follows：
![image](https://github.com/SpinalHDL/VexRiscv/assets/143673576/bbce6c58-4f63-4bbe-8b86-420649873002)
![image](https://github.com/SpinalHDL/VexRiscv/assets/143673576/b07a8138-9f9c-4f0f-8624-2715322c67dc)
How can I solve this problem？

**Comment by Dolu1990** [comment]
Hi,

Before using the FPU, in the software, you need to set the mstatus FS bits to something other than 00, else the FPU is disabled and will make things trap

**Comment by 15936866194** [comment]
Thank you for your answer. I used the generated.v file and vcs+verdi tool for simulation, but I am not very good at software Settings. What should I do for the problems you mentioned?
![image](https://github.com/SpinalHDL/VexRiscv/assets/143673576/42cc33dc-c40f-4abf-824c-e4e07e602eda)
I found the fs description in FpuPlugin, can I manipulate it to fix the problem?

**Comment by 15936866194** [comment]
I'm sorry, I didn't understand what you meant before, but now I do. Let me try

**Comment by Dolu1990** [comment]
Cool ^^
