### ISSUE TITLE
DBusSimplePlugin's Wishbone support forces 32-bit reads

### ISSUE THREAD

**Issue by kivikakk** [SpinalHDL/VexRiscv#426]
I notice that `DBusSimplePlugin`'s Wishbone bridge forces all reads to appear to be 32-bits wide:

https://github.com/SpinalHDL/VexRiscv/blob/0af9894e698288d65f6127c4a2806986dbabf09c/src/main/scala/vexriscv/plugin/DBusSimplePlugin.scala#L197-L199

I'm not sure of the exact reason it was done this way, but I'm wondering if you'd be amenable to changing this default! For some MMIO it's helpful to be able to distinguish the read size.

**Comment by Dolu1990** [comment]
Hmm i think you are right, this shouldn't be necessary to have this force to "1111"
Can you give a try without those 3 lines ?

**Comment by kivikakk** [comment]
Yes, in fact I'm doing that on my fork, and it works perfectly well! I'll make a PR if you like?

**Comment by Dolu1990** [comment]
Sure thanks ^^
