### ISSUE TITLE
What tools are supported

### ISSUE THREAD

**Issue by allrighteveryday** [SpinalHDL/VexRiscv#428]
hi.I am a green hand and would like to know if Vexriscv supports DAP CMSIS or JLINK load software programs.

**Comment by Dolu1990** [comment]
Hi,
As long as the tool is supported by openocd, it should be fine.
=>  check openocd supports :D
One thing, VexRiscv is JTAG only.

**Comment by allrighteveryday** [comment]
> Hi, As long as the tool is supported by openocd, it should be fine. => check openocd supports :D One thing, VexRiscv is JTAG only.

thanks！
