### ISSUE TITLE
SiFive GCC link in Readme.md is dead.

### ISSUE THREAD

**Issue by jahagirdar** [SpinalHDL/VexRiscv#429]
The readme recommends, https://www.sifive.com/software/ "Prebuilt RISC‑V GCC Toolchain and Emulator" as the path to download the gcc toolchain.
The text no longer exists on that page. All the links on the page go to a registration page followed by https://scs.sifive.com/ which only has a link to download their cores.
The nearest source for the sifive tools would be https://github.com/sifive/freedom-tools which is archived and only contains instructions to build the gcc toolchain from source.

**Comment by Dolu1990** [comment]
thanks :)
