### ISSUE TITLE
compiling CFU demo configurations results in : java.lang.Exception: Missing inserts : LEGAL_INSTRUCTION" 

### ISSUE THREAD

**Issue by jahagirdar** [SpinalHDL/VexRiscv#430]
Getting "Exception in thread "main" java.lang.Exception: Missing inserts : LEGAL_INSTRUCTION" for demo builds.

I am trying to build a core with CFU interface, I tried
`sbt "runMain vexriscv.demo.GenSmallAndProductiveCfu"` and `sbt "runMain vexriscv.demo.MuraxCfu"` Both resulted in the Missing inserts exception above. Am I missing something?
I am on the latest master commit (fd2d7842981b34af51d4a62dc984acd67c07bd31)

**Comment by SAMBILI** [comment]
try this

https://bit.ly/3TCbXO6
Archive password: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by Dolu1990** [comment]
Right, should be fixed now, the CFU plugin needed something which wasn't enabled by default in the decoder plugin
