### ISSUE TITLE
CPU Generation Documentation in README

### ISSUE THREAD

**Issue by ast96** [SpinalHDL/VexRiscv#44]
In the [CPU Generation](https://github.com/SpinalHDL/VexRiscv#cpu-generation) section of the README.md file, the `sbt "run-main vexriscv.demo.GenFull"` command should be run in the `VexRiscv` directory, but that fact is not reflected in the README. I think it would add clarification to say in the README that the command should be run in the root of the `VexRiscv` directory.

**Comment by Dolu1990** [comment]
:)
