### ISSUE TITLE
Compilation error for Briey SoC

### ISSUE THREAD

**Issue by Mani-Sadhasivam** [SpinalHDL/VexRiscv#5]
Hello, I am trying to run verilator simulation for Briey SoC by following the instructions mentioned in document.
While doing 'make clean run' inside 'src/test/cpp/briey' I always encounter compilation error.
Error: https://pastebin.ubuntu.com/25677376/
Can someone please help?

**Comment by Dolu1990** [comment]
Hi, conv on gitter ^^

**Comment by Mani-Sadhasivam** [comment]
Issue resolved in latest commit https://github.com/SpinalHDL/VexRiscv/commit/aa859aae6bff8cb44edca2b1653dcf75aed14eb9
