### ISSUE TITLE
Source for muraxDemo.hex

### ISSUE THREAD

**Issue by lawrie** [SpinalHDL/VexRiscv#55]
Where is the source and makefile for https://github.com/SpinalHDL/VexRiscv/blob/master/src/main/ressource/hex/muraxDemo.hex?

https://github.com/SpinalHDL/VexRiscv/blob/master/src/main/c/murax/xipBootloader/demo.S looks as if it is doing something similar but does not copy the UART RX to TX, its makefile produces an elf file, but no hex file, and its elf file, demo.elf, is much small that muraxDemo.elf.

Apologies if I am missing something obvious - I have only just started looking at SpinalHDL.

**Comment by Dolu1990** [comment]
Hi,

No worries, it is comming from https://github.com/SpinalHDL/VexRiscvSocSoftware/tree/master/projects/murax/demo

The xipBootloader/demo was a very simple assembly programme used to check that the SoC was booting properly on its optional onchip ROM.

**Comment by lawrie** [comment]
I think I have found it at https://github.com/SpinalHDL/VexRiscvSocSoftware/blob/master/projects/murax/demo/src/main.c
