### ISSUE TITLE
JTAG input clock has not buffer

### ISSUE THREAD

**Issue by FlyingxDutch** [SpinalHDL/VexRiscv#72]

**Comment by FlyingxDutch** [comment]
Hello,
I encountered dificulties related to input signal of Briey SOC named:  io_jtag_tck. This signal has not buffer and cause error during implemenattion on FPGA board (with Xilinx Spartan6 device). For syntessis I am using Xilinx ISE Webpacvk 14.7.

**Comment by Dolu1990** [comment]
Hoo, yes, Xilinx IDE is picky about getting a clock in the FPGA if the pin isn't a global buffer. But in the given case, that's fine, you can ask him to ignore it, as the JTAG is realy slow, and jtag IO have realy large setup times :)

**Comment by FlyingxDutch** [comment]
Hi,
I just added buffor primitive in project, so it solved the issue.
Best Regards
